// Карточки для интервального повторения: front — вопрос, back — ответ.
import type { SubjectId } from "./tasks";

export type Card = { id: string; subj: SubjectId; front: string; back: string; en?: { front: string; back: string } };

export const CARDS: Card[] = [
  // История — опорные даты
  {id:"hc1", subj:"hist", front:"Призвание варягов (Рюрик)", back:"862 г. — начало династии Рюриковичей",
   en:{front:"Calling of the Varangians (Rurik)", back:"862 — start of the Rurikid dynasty"}},
  {id:"hc2", subj:"hist", front:"Крещение Руси", back:"988 г. — князь Владимир",
   en:{front:"Baptism of Rus", back:"988 — Prince Vladimir"}},
  {id:"hc3", subj:"hist", front:"Куликовская битва", back:"1380 г. — Дмитрий Донской разбил Мамая",
   en:{front:"Battle of Kulikovo", back:"1380 — Dmitry Donskoy defeated Mamai"}},
  {id:"hc4", subj:"hist", front:"Стояние на реке Угре", back:"1480 г. — конец ордынской зависимости, Иван III",
   en:{front:"Great Stand on the Ugra River", back:"1480 — end of dependence on the Horde, Ivan III"}},
  {id:"hc5", subj:"hist", front:"Венчание Ивана IV на царство", back:"1547 г. — первый русский царь",
   en:{front:"Coronation of Ivan IV as tsar", back:"1547 — the first Russian tsar"}},
  {id:"hc6", subj:"hist", front:"Избрание Михаила Романова на царство", back:"1613 г. — Земский собор, конец Смуты",
   en:{front:"Election of Mikhail Romanov as tsar", back:"1613 — Zemsky Sobor, end of the Time of Troubles"}},
  {id:"hc7", subj:"hist", front:"Соборное уложение", back:"1649 г. — Алексей Михайлович, окончательное закрепощение крестьян",
   en:{front:"Sobornoye Ulozheniye (Council Code)", back:"1649 — Alexei Mikhailovich, final enserfment of peasants"}},
  {id:"hc8", subj:"hist", front:"Полтавская битва", back:"1709 г. — Пётр I разбил шведов Карла XII",
   en:{front:"Battle of Poltava", back:"1709 — Peter I defeated the Swedes of Charles XII"}},
  {id:"hc9", subj:"hist", front:"Отечественная война с Наполеоном", back:"1812 г. — Бородинское сражение, М. И. Кутузов",
   en:{front:"Patriotic War against Napoleon", back:"1812 — Battle of Borodino, M. I. Kutuzov"}},
  {id:"hc10", subj:"hist", front:"Отмена крепостного права", back:"1861 г. — Александр II, 19 февраля",
   en:{front:"Abolition of serfdom", back:"1861 — Alexander II, 19 February"}},
  {id:"hc11", subj:"hist", front:"Образование СССР", back:"1922 г. — 30 декабря",
   en:{front:"Formation of the USSR", back:"1922 — 30 December"}},
  {id:"hc12", subj:"hist", front:"Великая Отечественная война", back:"22 июня 1941 г. — 9 мая 1945 г.",
   en:{front:"Great Patriotic War", back:"22 June 1941 — 9 May 1945"}},
  {id:"hc13", subj:"hist", front:"Первый полёт человека в космос", back:"12 апреля 1961 г. — Ю. А. Гагарин",
   en:{front:"First human spaceflight", back:"12 April 1961 — Yuri Gagarin"}},
  {id:"hc14", subj:"hist", front:"Принятие Конституции РФ", back:"12 декабря 1993 г. — всенародное голосование",
   en:{front:"Adoption of the Russian Constitution", back:"12 December 1993 — nationwide vote"}},

  // Обществознание — термины
  {id:"sc1", subj:"soc", front:"Социализация", back:"Усвоение человеком норм, ценностей и социальных ролей общества",
   en:{front:"Socialization", back:"Learning society's norms, values and social roles"}},
  {id:"sc2", subj:"soc", front:"Мировоззрение", back:"Система взглядов человека на мир и своё место в нём",
   en:{front:"Worldview", back:"A person's system of views on the world and their place in it"}},
  {id:"sc3", subj:"soc", front:"Социальная мобильность", back:"Перемещение людей или групп в социальной структуре общества",
   en:{front:"Social mobility", back:"Movement of people or groups within the social structure"}},
  {id:"sc4", subj:"soc", front:"Инфляция", back:"Устойчивый рост общего уровня цен; деньги теряют покупательную способность",
   en:{front:"Inflation", back:"A sustained rise in the general price level; money loses purchasing power"}},
  {id:"sc5", subj:"soc", front:"Монополия", back:"Рынок, на котором действует один продавец",
   en:{front:"Monopoly", back:"A market with a single seller"}},
  {id:"sc6", subj:"soc", front:"Факторы производства", back:"Труд, земля, капитал, предпринимательские способности, информация",
   en:{front:"Factors of production", back:"Labour, land, capital, entrepreneurial ability, information"}},
  {id:"sc7", subj:"soc", front:"ВВП (валовой внутренний продукт)", back:"Рыночная стоимость всех конечных товаров и услуг, произведённых в стране за год",
   en:{front:"GDP (gross domestic product)", back:"Market value of all final goods and services produced in a country in a year"}},
  {id:"sc8", subj:"soc", front:"Правоспособность", back:"Способность иметь права и обязанности; возникает с рождения",
   en:{front:"Passive legal capacity (pravosposobnost)", back:"The ability to have rights and duties; arises at birth"}},
  {id:"sc9", subj:"soc", front:"Дееспособность", back:"Способность своими действиями приобретать и осуществлять права и обязанности",
   en:{front:"Active legal capacity (deesposobnost)", back:"The ability to acquire and exercise rights and duties by one's own actions"}},
  {id:"sc10", subj:"soc", front:"Правонарушение", back:"Виновное противоправное деяние деликтоспособного лица",
   en:{front:"Offence", back:"A culpable unlawful act by a person legally capable of bearing responsibility"}},
  {id:"sc11", subj:"soc", front:"Суверенитет государства", back:"Верховенство власти внутри страны и независимость во внешних делах",
   en:{front:"State sovereignty", back:"Supreme authority at home and independence in external affairs"}},
  {id:"sc12", subj:"soc", front:"Федерация", back:"Форма государственного устройства: союз субъектов с определённой самостоятельностью",
   en:{front:"Federation", back:"Form of territorial structure: a union of constituent units with some autonomy"}},
  {id:"sc13", subj:"soc", front:"Демократия", back:"Политический режим, при котором источником власти признаётся народ",
   en:{front:"Democracy", back:"A political regime in which the people are recognised as the source of power"}},
  {id:"sc14", subj:"soc", front:"Сроки полномочий Президента РФ и Госдумы", back:"Президент — 6 лет, Государственная Дума — 5 лет",
   en:{front:"Terms of the Russian President and State Duma", back:"President — 6 years, State Duma — 5 years"}},

  // Биология
  {id:"bc1", subj:"bio", front:"Фотосинтез", back:"Синтез органических веществ из CO₂ и H₂O на свету; идёт в хлоропластах",
   en:{front:"Photosynthesis", back:"Making organic matter from CO₂ and H₂O using light; takes place in chloroplasts"}},
  {id:"bc2", subj:"bio", front:"Митоз", back:"Деление, дающее две клетки с тем же набором хромосом, что у материнской",
   en:{front:"Mitosis", back:"Division giving two cells with the same chromosome set as the parent cell"}},
  {id:"bc3", subj:"bio", front:"Мейоз", back:"Два деления подряд: из диплоидной клетки — четыре гаплоидные",
   en:{front:"Meiosis", back:"Two divisions in a row: one diploid cell gives four haploid cells"}},
  {id:"bc4", subj:"bio", front:"Генотип и фенотип", back:"Генотип — совокупность генов, фенотип — совокупность признаков организма",
   en:{front:"Genotype and phenotype", back:"Genotype is the set of genes, phenotype the set of an organism's traits"}},
  {id:"bc5", subj:"bio", front:"Аллельные гены", back:"Гены в одинаковых локусах гомологичных хромосом, отвечающие за один признак",
   en:{front:"Alleles", back:"Genes at the same loci of homologous chromosomes controlling one trait"}},
  {id:"bc6", subj:"bio", front:"Принцип комплементарности в ДНК", back:"А–Т, Г–Ц; в РНК вместо Т — У",
   en:{front:"Complementarity in DNA", back:"A–T, G–C; in RNA U replaces T"}},
  {id:"bc7", subj:"bio", front:"Набор хромосом человека", back:"2n = 46 в соматических клетках, n = 23 в гаметах",
   en:{front:"Human chromosome number", back:"2n = 46 in somatic cells, n = 23 in gametes"}},
  {id:"bc8", subj:"bio", front:"Продуценты", back:"Создают органику из неорганических веществ: растения, водоросли, цианобактерии",
   en:{front:"Producers", back:"Make organic matter from inorganic substances: plants, algae, cyanobacteria"}},
  {id:"bc9", subj:"bio", front:"Правило экологической пирамиды", back:"На следующий трофический уровень переходит около 10 % энергии",
   en:{front:"Ecological pyramid rule", back:"About 10% of the energy passes to the next trophic level"}},
  {id:"bc10", subj:"bio", front:"Гомологичные органы", back:"Общее происхождение, разные функции: рука человека и крыло летучей мыши",
   en:{front:"Homologous organs", back:"Common origin, different functions: a human arm and a bat's wing"}},
  {id:"bc11", subj:"bio", front:"Аналогичные органы", back:"Сходные функции, разное происхождение: крыло бабочки и крыло птицы",
   en:{front:"Analogous organs", back:"Similar functions, different origins: a butterfly's wing and a bird's wing"}},
  {id:"bc12", subj:"bio", front:"Автор теории естественного отбора", back:"Чарльз Дарвин — «Происхождение видов», 1859 г.",
   en:{front:"Author of the theory of natural selection", back:"Charles Darwin — On the Origin of Species, 1859"}},
  {id:"bc13", subj:"bio", front:"Инсулин", back:"Гормон поджелудочной железы; понижает уровень глюкозы в крови",
   en:{front:"Insulin", back:"A pancreatic hormone; lowers blood glucose"}},
  {id:"bc14", subj:"bio", front:"Гемоглобин", back:"Железосодержащий белок эритроцитов; переносит кислород",
   en:{front:"Haemoglobin", back:"Iron-containing protein of red blood cells; carries oxygen"}},

  // Химия
  {id:"cc1", subj:"chem", front:"Число Авогадро", back:"Nₐ = 6,02·10²³ моль⁻¹",
   en:{front:"Avogadro's number", back:"Nₐ = 6.02·10²³ mol⁻¹"}},
  {id:"cc2", subj:"chem", front:"Молярный объём газа при н. у.", back:"Vm = 22,4 л/моль",
   en:{front:"Molar volume of a gas at STP", back:"Vm = 22.4 L/mol"}},
  {id:"cc3", subj:"chem", front:"Нормальные условия (н. у.)", back:"0 °C (273 К) и 101,3 кПа",
   en:{front:"Standard conditions (STP)", back:"0 °C (273 K) and 101.3 kPa"}},
  {id:"cc4", subj:"chem", front:"Количество вещества", back:"n = m / M = V / Vm = N / Nₐ",
   en:{front:"Amount of substance", back:"n = m / M = V / Vm = N / Nₐ"}},
  {id:"cc5", subj:"chem", front:"Массовая доля вещества в растворе", back:"ω = m(вещества) / m(раствора) · 100 %",
   en:{front:"Mass fraction of a solute", back:"ω = m(solute) / m(solution) · 100%"}},
  {id:"cc6", subj:"chem", front:"Серная кислота", back:"H₂SO₄; соли — сульфаты",
   en:{front:"Sulfuric acid", back:"H₂SO₄; its salts are sulfates"}},
  {id:"cc7", subj:"chem", front:"Азотная кислота", back:"HNO₃; соли — нитраты",
   en:{front:"Nitric acid", back:"HNO₃; its salts are nitrates"}},
  {id:"cc8", subj:"chem", front:"Соляная кислота", back:"HCl; соли — хлориды",
   en:{front:"Hydrochloric acid", back:"HCl; its salts are chlorides"}},
  {id:"cc9", subj:"chem", front:"Гашёная известь", back:"Ca(OH)₂ — гидроксид кальция",
   en:{front:"Slaked lime", back:"Ca(OH)₂ — calcium hydroxide"}},
  {id:"cc10", subj:"chem", front:"Негашёная известь", back:"CaO — оксид кальция",
   en:{front:"Quicklime", back:"CaO — calcium oxide"}},
  {id:"cc11", subj:"chem", front:"Ионная связь", back:"Между типичным металлом и типичным неметаллом: NaCl, CaF₂",
   en:{front:"Ionic bond", back:"Between a typical metal and a typical non-metal: NaCl, CaF₂"}},
  {id:"cc12", subj:"chem", front:"Ковалентная неполярная связь", back:"Между атомами одного неметалла: H₂, O₂, Cl₂",
   en:{front:"Non-polar covalent bond", back:"Between atoms of the same non-metal: H₂, O₂, Cl₂"}},
  {id:"cc13", subj:"chem", front:"Реакция нейтрализации", back:"Кислота + основание → соль + вода",
   en:{front:"Neutralization reaction", back:"Acid + base → salt + water"}},
  {id:"cc14", subj:"chem", front:"Самый электроотрицательный элемент", back:"Фтор F",
   en:{front:"The most electronegative element", back:"Fluorine F"}},

  // Физика
  {id:"pc1", subj:"phys", front:"Второй закон Ньютона", back:"F = ma; сила в ньютонах (Н)",
   en:{front:"Newton's second law", back:"F = ma; force in newtons (N)"}},
  {id:"pc2", subj:"phys", front:"Скорость при равноускоренном движении", back:"v = v₀ + at",
   en:{front:"Velocity in uniformly accelerated motion", back:"v = v₀ + at"}},
  {id:"pc3", subj:"phys", front:"Перемещение при равноускоренном движении", back:"s = v₀t + at²/2",
   en:{front:"Displacement in uniformly accelerated motion", back:"s = v₀t + at²/2"}},
  {id:"pc4", subj:"phys", front:"Кинетическая энергия", back:"Eк = mv²/2, Дж",
   en:{front:"Kinetic energy", back:"Ek = mv²/2, J"}},
  {id:"pc5", subj:"phys", front:"Потенциальная энергия тела над Землёй", back:"Eп = mgh, Дж",
   en:{front:"Potential energy of a body above the Earth", back:"Ep = mgh, J"}},
  {id:"pc6", subj:"phys", front:"Импульс тела", back:"p = mv, кг·м/с",
   en:{front:"Momentum of a body", back:"p = mv, kg·m/s"}},
  {id:"pc7", subj:"phys", front:"Механическая мощность", back:"N = A / t, Вт",
   en:{front:"Mechanical power", back:"P = A / t, W (A is work)"}},
  {id:"pc8", subj:"phys", front:"Давление", back:"p = F / S, Па",
   en:{front:"Pressure", back:"p = F / S, Pa"}},
  {id:"pc9", subj:"phys", front:"Количество теплоты при нагревании", back:"Q = cmΔt, Дж",
   en:{front:"Heat needed to warm a body", back:"Q = cmΔt, J"}},
  {id:"pc10", subj:"phys", front:"Уравнение Менделеева–Клапейрона", back:"pV = (m/M)·RT = νRT",
   en:{front:"Ideal gas law (Mendeleev–Clapeyron equation)", back:"pV = (m/M)·RT = νRT"}},
  {id:"pc11", subj:"phys", front:"Закон Ома для участка цепи", back:"I = U / R",
   en:{front:"Ohm's law for a section of a circuit", back:"I = U / R"}},
  {id:"pc12", subj:"phys", front:"Закон Джоуля–Ленца", back:"Q = I²Rt, Дж",
   en:{front:"Joule–Lenz law", back:"Q = I²Rt, J"}},
  {id:"pc13", subj:"phys", front:"Оптическая сила линзы", back:"D = 1 / F, дптр (F — в метрах)",
   en:{front:"Optical power of a lens", back:"D = 1 / F, dioptres (F in metres)"}},
  {id:"pc14", subj:"phys", front:"Скорость света в вакууме", back:"c ≈ 3·10⁸ м/с",
   en:{front:"Speed of light in a vacuum", back:"c ≈ 3·10⁸ m/s"}},

  // Математика
  {id:"mc1", subj:"math", front:"Дискриминант уравнения ax² + bx + c = 0", back:"D = b² − 4ac",
   en:{front:"Discriminant of ax² + bx + c = 0", back:"D = b² − 4ac"}},
  {id:"mc2", subj:"math", front:"Корни квадратного уравнения", back:"x = (−b ± √D) / (2a), если D ≥ 0",
   en:{front:"Roots of a quadratic equation", back:"x = (−b ± √D) / (2a), if D ≥ 0"}},
  {id:"mc3", subj:"math", front:"Теорема Виета для x² + px + q = 0", back:"x₁ + x₂ = −p, x₁·x₂ = q",
   en:{front:"Vieta's theorem for x² + px + q = 0", back:"x₁ + x₂ = −p, x₁·x₂ = q"}},
  {id:"mc4", subj:"math", front:"Формула квадрата суммы", back:"(a + b)² = a² + 2ab + b²",
   en:{front:"Square of a sum", back:"(a + b)² = a² + 2ab + b²"}},
  {id:"mc5", subj:"math", front:"Разность квадратов", back:"a² − b² = (a − b)(a + b)",
   en:{front:"Difference of squares", back:"a² − b² = (a − b)(a + b)"}},
  {id:"mc6", subj:"math", front:"Теорема Пифагора", back:"c² = a² + b², где c — гипотенуза",
   en:{front:"Pythagorean theorem", back:"c² = a² + b², where c is the hypotenuse"}},
  {id:"mc7", subj:"math", front:"Площадь треугольника", back:"S = ½·a·h, h — высота к стороне a",
   en:{front:"Area of a triangle", back:"S = ½·a·h, h is the height to side a"}},
  {id:"mc8", subj:"math", front:"Площадь трапеции", back:"S = (a + b)/2 · h, a и b — основания",
   en:{front:"Area of a trapezoid", back:"S = (a + b)/2 · h, a and b are the bases"}},
  {id:"mc9", subj:"math", front:"Площадь круга и длина окружности", back:"S = πr², C = 2πr",
   en:{front:"Area and circumference of a circle", back:"S = πr², C = 2πr"}},
  {id:"mc10", subj:"math", front:"n-й член арифметической прогрессии", back:"aₙ = a₁ + d(n − 1)",
   en:{front:"nth term of an arithmetic progression", back:"aₙ = a₁ + d(n − 1)"}},
  {id:"mc11", subj:"math", front:"Сумма n первых членов арифметической прогрессии", back:"Sₙ = (a₁ + aₙ)·n / 2",
   en:{front:"Sum of the first n terms of an arithmetic progression", back:"Sₙ = (a₁ + aₙ)·n / 2"}},
  {id:"mc12", subj:"math", front:"n-й член геометрической прогрессии", back:"bₙ = b₁·qⁿ⁻¹",
   en:{front:"nth term of a geometric progression", back:"bₙ = b₁·qⁿ⁻¹"}},
  {id:"mc13", subj:"math", front:"sin 30°, cos 30°, tg 45°", back:"½; √3/2; 1",
   en:{front:"sin 30°, cos 30°, tan 45°", back:"½; √3/2; 1"}},
  {id:"mc14", subj:"math", front:"Основное тригонометрическое тождество", back:"sin²α + cos²α = 1",
   en:{front:"Pythagorean trigonometric identity", back:"sin²α + cos²α = 1"}},

  // Русский язык
  {id:"rc1", subj:"rus", front:"Ударение: звонит", back:"звонИт",
   en:{front:"Stress: звонит", back:"звонИт — stress on the ending"}},
  {id:"rc2", subj:"rus", front:"Ударение: торты", back:"тОрты",
   en:{front:"Stress: торты", back:"тОрты — fixed stress on the stem"}},
  {id:"rc3", subj:"rus", front:"Ударение: красивее", back:"красИвее",
   en:{front:"Stress: красивее", back:"красИвее — same stress as красИвый"}},
  {id:"rc4", subj:"rus", front:"Ударение: щавель", back:"щавЕль",
   en:{front:"Stress: щавель", back:"щавЕль — second syllable"}},
  {id:"rc5", subj:"rus", front:"Ударение: кухонный", back:"кУхонный",
   en:{front:"Stress: кухонный", back:"кУхонный — first syllable"}},
  {id:"rc6", subj:"rus", front:"Ударение: договор", back:"договОр",
   en:{front:"Stress: договор", back:"договОр — last syllable"}},
  {id:"rc7", subj:"rus", front:"Ударение: обеспечение", back:"обеспЕчение",
   en:{front:"Stress: обеспечение", back:"обеспЕчение — third syllable"}},
  {id:"rc8", subj:"rus", front:"Ударение: включит", back:"включИт",
   en:{front:"Stress: включит", back:"включИт — stress on the ending"}},
  {id:"rc9", subj:"rus", front:"Ударение: жалюзи", back:"жалюзИ",
   en:{front:"Stress: жалюзи", back:"жалюзИ — last syllable"}},
  {id:"rc10", subj:"rus", front:"Ударение: километр", back:"киломЕтр",
   en:{front:"Stress: километр", back:"киломЕтр — like метр"}},
  {id:"rc11", subj:"rus", front:"НН в суффиксах -ан-, -ян-: исключения", back:"стеклянный, оловянный, деревянный",
   en:{front:"НН with suffixes -ан-, -ян-: exceptions", back:"стеклянный, оловянный, деревянный — the only three"}},
  {id:"rc12", subj:"rus", front:"Корень -раст-/-рос-: исключения", back:"росток, ростовщик, отрасль, Ростов, Ростислав",
   en:{front:"Root -раст-/-рос-: exceptions", back:"росток, ростовщик, отрасль, Ростов, Ростислав"}},
  {id:"rc13", subj:"rus", front:"Ы после Ц в корне: исключения", back:"цыган, цыплёнок, на цыпочках, цыкнуть, цыц",
   en:{front:"Ы after Ц in a root: exceptions", back:"цыган, цыплёнок, на цыпочках, цыкнуть, цыц"}},
  {id:"rc14", subj:"rus", front:"-тся или -ться?", back:"Что делать? — ться (инфинитив); что делает? — тся",
   en:{front:"-тся or -ться?", back:"Что делать? (infinitive) — ться; что делает? (3rd person) — тся"}},
];
