// Дополнительные задания тренажёра (формат как в tasks.ts).
// Задания составлены в стиле первой части ЕГЭ/ОГЭ, это не копии из открытого банка ФИПИ.
import type { Task } from "./tasks";

export type TaskEnX = { topic: string; q: string; answers?: string[]; exp: string };

export const TASKS_EXTRA: Task[] = [
  // История
  {id:"h7", subj:"hist", topic:"Древняя Русь", q:"В каком году Москва впервые упоминается в летописи?", answers:["1147","1147 г","1147 год"],
   exp:"Под 1147 годом летопись сообщает, что Юрий Долгорукий позвал в Москву своего союзника Святослава Ольговича. Эту дату и считают годом основания Москвы."},
  {id:"h8", subj:"hist", topic:"Борьба с крестоносцами", q:"В каком году произошло Ледовое побоище на Чудском озере?", answers:["1242","1242 г","1242 год"],
   exp:"5 апреля 1242 года Александр Невский разбил рыцарей Ливонского ордена на льду Чудского озера. Двумя годами раньше, в 1240 году, была Невская битва со шведами."},
  {id:"h9", subj:"hist", topic:"Россия при Петре I", q:"Выберите два события, которые произошли в правление Петра I. Запишите цифры.\n1) Полтавская битва\n2) принятие Соборного уложения\n3) стояние на реке Угре\n4) отмена местничества\n5) основание Санкт-Петербурга", answers:["15","51"],
   exp:"Санкт-Петербург основан в 1703 году, Полтавская битва — 1709 год, оба события при Петре I. Соборное уложение принято в 1649 году при Алексее Михайловиче, местничество отменено в 1682 году при Фёдоре Алексеевиче, стояние на Угре — 1480 год, Иван III."},
  {id:"h10", subj:"hist", topic:"СССР в 1920-е годы", q:"В каком году был образован СССР?", answers:["1922","1922 г","1922 год"],
   exp:"30 декабря 1922 года I съезд Советов СССР утвердил Декларацию и Договор об образовании СССР. Его учредили РСФСР, Украинская ССР, Белорусская ССР и ЗСФСР."},
  {id:"h11", subj:"hist", topic:"Великая Отечественная война", q:"Как называлась операция по окружению немецких войск под Сталинградом, начавшаяся 19 ноября 1942 года? (одно слово)", answers:["уран","операция уран"],
   exp:"Операция «Уран» завершилась окружением 6-й армии Паулюса. Сталинградская битва закончилась 2 февраля 1943 года и положила начало коренному перелому в войне."},
  {id:"h12", subj:"hist", topic:"Советская Россия", q:"Как называлась экономическая политика, которую провозгласил X съезд РКП(б) в 1921 году на смену «военному коммунизму»? Запишите аббревиатуру.", answers:["нэп","новая экономическая политика"],
   exp:"НЭП — новая экономическая политика. Её первым шагом стала замена продразвёрстки продналогом; были разрешены частная торговля и мелкое предпринимательство."},

  // Обществознание
  {id:"s6", subj:"soc", topic:"Экономика", q:"Как называется тип рынка, на котором действует только один продавец?", answers:["монополия","чистая монополия"],
   exp:"При монополии единственный продавец может влиять на цену. Если же продавцов немного (несколько крупных фирм) — это олигополия."},
  {id:"s7", subj:"soc", topic:"Экономика", q:"Выберите два понятия, которые относятся к факторам производства. Запишите цифры.\n1) спрос\n2) труд\n3) инфляция\n4) капитал\n5) налог", answers:["24","42"],
   exp:"Факторы производства — это труд, земля, капитал, предпринимательские способности и информация. Спрос, инфляция и налог — экономические понятия, но не ресурсы для производства."},
  {id:"s8", subj:"soc", topic:"Право", q:"Какая отрасль права регулирует имущественные и связанные с ними личные неимущественные отношения? (два слова)", answers:["гражданское право","гражданское"],
   exp:"Это гражданское право, его основной источник — Гражданский кодекс РФ. Сюда относятся собственность, договоры, наследование, защита чести и достоинства."},
  {id:"s9", subj:"soc", topic:"Политика", q:"На сколько лет избирается Президент Российской Федерации?", answers:["6","6 лет","шесть","шесть лет"],
   exp:"Президент избирается на 6 лет (статья 81 Конституции РФ), Государственная Дума — на 5 лет. Такие сроки действуют после поправок 2008 года."},
  {id:"s10", subj:"soc", topic:"Человек и общество", q:"Как называется процесс усвоения человеком норм, ценностей и социальных ролей, принятых в обществе?", answers:["социализация"],
   exp:"Социализация идёт всю жизнь. Первичная проходит в семье и среди близких, вторичная — в школе, вузе, на работе и в других социальных институтах."},
  {id:"s11", subj:"soc", topic:"Политика", q:"Выберите два органа, которые относятся к законодательной власти в РФ. Запишите цифры.\n1) Государственная Дума\n2) Правительство РФ\n3) Совет Федерации\n4) Конституционный Суд РФ\n5) Прокуратура РФ", answers:["13","31"],
   exp:"Парламент РФ — Федеральное Собрание — состоит из двух палат: Совета Федерации и Государственной Думы. Правительство — исполнительная власть, Конституционный Суд — судебная."},

  // Биология
  {id:"b6", subj:"bio", topic:"Клетка", q:"Как называется способ деления, при котором из одной диплоидной клетки образуются четыре гаплоидные?", answers:["мейоз"],
   exp:"Мейоз включает два деления подряд, и набор хромосом уменьшается вдвое. Митоз, наоборот, даёт две клетки с тем же набором, что у материнской."},
  {id:"b7", subj:"bio", topic:"Генетика", q:"Скрестили две гетерозиготные особи Aa × Aa при полном доминировании. Какой процент потомков будет иметь рецессивный фенотип?", answers:["25","25%","25 %"],
   exp:"Генотипы потомков: 1 AA : 2 Aa : 1 aa. Рецессивный признак проявляется только у aa — это 1 из 4, то есть 25 %."},
  {id:"b8", subj:"bio", topic:"Генетика", q:"Сколько типов гамет образует особь с генотипом AaBb, если гены не сцеплены?", answers:["4","четыре"],
   exp:"Гены наследуются независимо, поэтому образуются гаметы AB, Ab, aB и ab. Общая формула — 2ⁿ, где n — число пар генов в гетерозиготном состоянии: 2² = 4."},
  {id:"b9", subj:"bio", topic:"Эволюция", q:"Как называются органы, имеющие общее происхождение, но выполняющие разные функции (например, рука человека и крыло летучей мыши)?", answers:["гомологичные","гомологичные органы"],
   exp:"Гомологичные органы — доказательство общего происхождения видов. Аналогичные органы, наоборот, выполняют сходные функции, но развились из разных зачатков: крыло бабочки и крыло птицы."},
  {id:"b10", subj:"bio", topic:"Экология", q:"Выберите два организма, которые относятся к продуцентам. Запишите цифры.\n1) берёза\n2) заяц-русак\n3) гриб-трутовик\n4) хламидомонада\n5) волк", answers:["14","41"],
   exp:"Продуценты создают органические вещества из неорганических: это растения, водоросли (хламидомонада — одноклеточная зелёная водоросль) и цианобактерии. Заяц и волк — консументы, гриб — гетеротроф."},
  {id:"b11", subj:"bio", topic:"Человек", q:"Какой гормон поджелудочной железы понижает уровень глюкозы в крови?", answers:["инсулин"],
   exp:"Инсулин способствует переходу глюкозы в клетки и её запасанию в виде гликогена. Его антагонист глукагон, наоборот, повышает уровень глюкозы."},

  // Химия
  {id:"c6", subj:"chem", topic:"Строение атома", q:"Сколько электронов находится на внешнем энергетическом уровне атома фосфора?", answers:["5","пять"],
   exp:"Фосфор — элемент 3-го периода VA-группы, распределение электронов 2, 8, 5. У элементов главных подгрупп число внешних электронов равно номеру группы."},
  {id:"c7", subj:"chem", topic:"Химическая связь", q:"Выберите два вещества с ионной связью. Запишите цифры.\n1) NaCl\n2) HCl\n3) O₂\n4) CaF₂\n5) H₂O", answers:["14","41"],
   exp:"Ионная связь возникает между атомами типичного металла и типичного неметалла: NaCl и CaF₂. В HCl и H₂O связь ковалентная полярная, в O₂ — ковалентная неполярная."},
  {id:"c8", subj:"chem", topic:"Расчёты", q:"Вычислите массу 0,5 моль серной кислоты H₂SO₄. Ответ дайте в граммах.", answers:["49","49 г"],
   exp:"M(H₂SO₄) = 2·1 + 32 + 4·16 = 98 г/моль. m = n·M = 0,5 · 98 = 49 г."},
  {id:"c9", subj:"chem", topic:"Расчёты", q:"В 180 г воды растворили 20 г соли. Вычислите массовую долю соли в растворе (в процентах).", answers:["10","10%","10 %"],
   exp:"Масса раствора = 180 + 20 = 200 г. ω = 20 / 200 · 100 % = 10 %. Частая ошибка — делить на массу воды, а не раствора."},
  {id:"c10", subj:"chem", topic:"Реакции", q:"Как называется реакция между кислотой и основанием, в результате которой образуются соль и вода?", answers:["нейтрализация","реакция нейтрализации"],
   exp:"Пример: NaOH + HCl → NaCl + H₂O. Это частный случай реакции обмена; в сокращённом ионном виде: H⁺ + OH⁻ → H₂O."},
  {id:"c11", subj:"chem", topic:"Расчёты", q:"Какой объём занимают 2 моль любого газа при нормальных условиях? Ответ дайте в литрах.", answers:["44,8","44.8","44,8 л","44.8 л"],
   exp:"При н. у. молярный объём любого газа Vm = 22,4 л/моль. V = n·Vm = 2 · 22,4 = 44,8 л."},

  // Физика
  {id:"p6", subj:"phys", topic:"Кинематика", q:"Автомобиль, двигаясь равноускоренно из состояния покоя, за 4 с набрал скорость 20 м/с. Найдите его ускорение (в м/с²).", answers:["5","5 м/с2","5 м/с²"],
   exp:"a = (v − v₀) / t = (20 − 0) / 4 = 5 м/с². Начальная скорость равна нулю, потому что движение началось из состояния покоя."},
  {id:"p7", subj:"phys", topic:"Энергия", q:"Тело массой 2 кг движется со скоростью 3 м/с. Чему равна его кинетическая энергия (в джоулях)?", answers:["9","9 дж"],
   exp:"Eк = mv²/2 = 2 · 3² / 2 = 9 Дж. Не забудьте возвести скорость в квадрат — это самая частая ошибка."},
  {id:"p8", subj:"phys", topic:"Термодинамика", q:"Какое количество теплоты нужно, чтобы нагреть 2 кг воды на 10 °C? Удельная теплоёмкость воды 4200 Дж/(кг·°C). Ответ дайте в килоджоулях.", answers:["84","84 кдж"],
   exp:"Q = cmΔt = 4200 · 2 · 10 = 84 000 Дж = 84 кДж. Ответ просят в килоджоулях, поэтому делим на 1000."},
  {id:"p9", subj:"phys", topic:"Электричество", q:"Резисторы сопротивлением 3 Ом и 6 Ом соединены параллельно. Найдите общее сопротивление (в омах).", answers:["2","2 ом"],
   exp:"При параллельном соединении 1/R = 1/R₁ + 1/R₂, для двух резисторов R = R₁R₂ / (R₁ + R₂) = 18 / 9 = 2 Ом. Общее сопротивление меньше наименьшего из них."},
  {id:"p10", subj:"phys", topic:"Оптика", q:"Фокусное расстояние собирающей линзы 0,25 м. Чему равна её оптическая сила (в диоптриях)?", answers:["4","4 дптр"],
   exp:"D = 1 / F = 1 / 0,25 м = 4 дптр. Фокусное расстояние обязательно переводят в метры."},
  {id:"p11", subj:"phys", topic:"Общие вопросы", q:"Выберите два верных утверждения. Запишите цифры.\n1) При изобарном процессе давление газа остаётся постоянным.\n2) Сила тяжести измеряется в джоулях.\n3) Скорость света в вакууме приблизительно равна 3·10⁸ м/с.\n4) При последовательном соединении общее сопротивление меньше наименьшего из сопротивлений.\n5) Звук распространяется в вакууме.", answers:["13","31"],
   exp:"Верны 1 и 3. Сила измеряется в ньютонах; при последовательном соединении сопротивления складываются, и общее больше любого из них; звуку нужна среда, в вакууме он не распространяется."},

  // Математика
  {id:"m5", subj:"math", topic:"Вычисления", q:"Найдите значение выражения (2,4 − 0,9) · 6.", answers:["9"],
   exp:"Сначала скобки: 2,4 − 0,9 = 1,5. Затем 1,5 · 6 = 9."},
  {id:"m6", subj:"math", topic:"Уравнения", q:"Решите уравнение x² − 5x + 6 = 0. Если корней несколько, запишите больший из них.", answers:["3","x=3"],
   exp:"D = 25 − 24 = 1, x = (5 ± 1) / 2, то есть 2 и 3. По теореме Виета проверка: 2 + 3 = 5, 2 · 3 = 6. Больший корень — 3."},
  {id:"m7", subj:"math", topic:"Вероятность", q:"В коробке 20 шариков, из них 5 красных. Найдите вероятность того, что случайно выбранный шарик окажется красным.", answers:["0,25","0.25"],
   exp:"P = благоприятные исходы / все исходы = 5 / 20 = 0,25. Ответ в ОГЭ и ЕГЭ записывают десятичной дробью."},
  {id:"m8", subj:"math", topic:"Геометрия", q:"Катеты прямоугольного треугольника равны 6 и 8. Найдите гипотенузу.", answers:["10"],
   exp:"По теореме Пифагора c² = 6² + 8² = 36 + 64 = 100, c = 10. Тройку 6, 8, 10 полезно помнить — это удвоенная тройка 3, 4, 5."},
  {id:"m9", subj:"math", topic:"Проценты", q:"Товар стоил 800 рублей, затем его цену повысили на 15 %. Сколько рублей стал стоить товар?", answers:["920","920 р","920 руб","920 рублей"],
   exp:"15 % от 800 — это 800 · 0,15 = 120 рублей. Новая цена 800 + 120 = 920 рублей, или сразу 800 · 1,15 = 920."},
  {id:"m10", subj:"math", topic:"Функции", q:"Найдите значение функции y = 2x² − 3x при x = −2.", answers:["14"],
   exp:"y = 2 · (−2)² − 3 · (−2) = 2 · 4 + 6 = 14. Квадрат отрицательного числа положителен, а минус на минус даёт плюс."},

  // Русский язык
  {id:"r5", subj:"rus", topic:"Ударение", q:"В каком из слов ударение падает на второй слог: кухонный, щавель, баловать, обеспечение? Запишите это слово.", answers:["щавель"],
   exp:"Правильно: щавЕль, кУхонный, баловАть, обеспЕчение. В слове «обеспечение» ударение на третьем слоге, как и в «баловать»."},
  {id:"r6", subj:"rus", topic:"Корни с чередованием", q:"Укажите номера слов, в которых пропущена буква О. Запишите цифры.\n1) р..сток\n2) пол..гать\n3) з..ря\n4) к..снуться\n5) выр..щенный", answers:["14","41"],
   exp:"Росток — исключение из правила -раст-/-ращ-/-рос-, поэтому выращенный пишется с а. Коснуться — с о, так как после корня нет суффикса -а- (ср. касаться). Полагать (перед г — а), заря (без ударения — а)."},
  {id:"r7", subj:"rus", topic:"Правописание глаголов", q:"Что пишется в предложении «Он стара..(тся/ться) успеть к началу урока»? Напишите тся или ться.", answers:["тся"],
   exp:"Задаём вопрос: он что делает? — старается. Это форма 3-го лица, поэтому без ь. Мягкий знак пишется в инфинитиве: что делать? — стараться."},
  {id:"r8", subj:"rus", topic:"Пунктуация", q:"Сколько запятых нужно поставить в предложении: «Мы шли по дороге и разговаривали а солнце уже садилось за лес»? Запишите число.", answers:["1","одна","одну"],
   exp:"«Шли и разговаривали» — однородные сказуемые с одиночным союзом и, запятая не нужна. Перед а соединяются две грамматические основы, здесь нужна запятая: «…разговаривали, а солнце уже садилось за лес»."},
  {id:"r9", subj:"rus", topic:"Лексика", q:"Какой глагол нужно употребить в сочетании «… пальто» (на себя): надеть или одеть?", answers:["надеть"],
   exp:"Надеть что-то на себя (пальто, шапку), а одеть кого-то (ребёнка, куклу). Запоминалка: «Надеть одежду, одеть Надежду»."},
  {id:"r10", subj:"rus", topic:"Лексика", q:"Как называются слова, одинаковые по звучанию и написанию, но совершенно разные по значению (ключ от двери и ключ — родник)?", answers:["омонимы"],
   exp:"Это омонимы: значения между собой не связаны. У многозначного слова, наоборот, значения связаны общим признаком (ножка стула и ножка человека)."},
];

// ---------- Английская версия дополнительных заданий ----------
export const EN_EXTRA: Record<string, TaskEnX> = {
  h7: { topic: "Kievan Rus", q: "In what year is Moscow first mentioned in the chronicles?", answers: ["1147 ad"],
    exp: "Under the year 1147 the chronicle says that Yuri Dolgoruky invited his ally Svyatoslav Olgovich to Moscow. This date is taken as the year Moscow was founded." },
  h8: { topic: "Struggle against the crusaders", q: "In what year did the Battle on the Ice on Lake Peipus take place?", answers: ["1242 ad"],
    exp: "On 5 April 1242 Alexander Nevsky defeated the knights of the Livonian Order on the ice of Lake Peipus. Two years earlier, in 1240, came the Battle of the Neva against the Swedes." },
  h9: { topic: "Russia under Peter I", q: "Choose two events that took place during the reign of Peter I. Write the numbers.\n1) Battle of Poltava\n2) adoption of the Sobornoye Ulozheniye (Council Code)\n3) Great Stand on the Ugra River\n4) abolition of mestnichestvo (precedence system)\n5) founding of Saint Petersburg",
    exp: "Saint Petersburg was founded in 1703 and the Battle of Poltava was fought in 1709, both under Peter I. The Council Code was adopted in 1649 under Alexei Mikhailovich, mestnichestvo was abolished in 1682 under Fyodor Alexeyevich, and the Stand on the Ugra was in 1480 under Ivan III." },
  h10: { topic: "USSR in the 1920s", q: "In what year was the USSR formed?", answers: ["1922 ad"],
    exp: "On 30 December 1922 the First Congress of Soviets of the USSR approved the Declaration and Treaty on the Formation of the USSR. Its founders were the RSFSR, the Ukrainian SSR, the Byelorussian SSR and the Transcaucasian SFSR." },
  h11: { topic: "Great Patriotic War", q: "What was the name of the operation to encircle German troops at Stalingrad that began on 19 November 1942? (one word)", answers: ["uranus", "operation uranus"],
    exp: "Operation Uranus ended with the encirclement of Paulus's 6th Army. The Battle of Stalingrad ended on 2 February 1943 and began the radical turning point of the war." },
  h12: { topic: "Soviet Russia", q: "What was the economic policy proclaimed by the 10th Congress of the RCP(b) in 1921 to replace War Communism called? Write the abbreviation.", answers: ["nep", "new economic policy"],
    exp: "NEP is the New Economic Policy. Its first step was replacing grain requisitioning with a tax in kind; private trade and small businesses were allowed." },
  s6: { topic: "Economics", q: "What is a market with only one seller called?", answers: ["monopoly", "pure monopoly"],
    exp: "Under a monopoly the single seller can influence the price. If there are only a few large sellers, it is an oligopoly." },
  s7: { topic: "Economics", q: "Choose two terms that are factors of production. Write the numbers.\n1) demand\n2) labour\n3) inflation\n4) capital\n5) tax",
    exp: "The factors of production are labour, land, capital, entrepreneurial ability and information. Demand, inflation and tax are economic concepts, but not resources used in production." },
  s8: { topic: "Law", q: "Which branch of law regulates property relations and the personal non-property relations linked to them? (two words)", answers: ["civil law", "civil"],
    exp: "This is civil law, and its main source is the Civil Code of the Russian Federation. It covers property, contracts, inheritance, and protection of honour and dignity." },
  s9: { topic: "Politics", q: "For how many years is the President of the Russian Federation elected?", answers: ["6 years", "six", "six years"],
    exp: "The President is elected for 6 years (Article 81 of the Constitution), the State Duma for 5 years. These terms have applied since the 2008 amendments." },
  s10: { topic: "Individual and society", q: "What is the process by which a person learns the norms, values and social roles accepted in society called?", answers: ["socialization", "socialisation"],
    exp: "Socialization lasts a lifetime. Primary socialization happens in the family and among close people, secondary — at school, university, work and in other social institutions." },
  s11: { topic: "Politics", q: "Choose two bodies that belong to the legislative branch in Russia. Write the numbers.\n1) State Duma\n2) Government of the Russian Federation\n3) Federation Council\n4) Constitutional Court\n5) Prosecutor's Office",
    exp: "Russia's parliament, the Federal Assembly, has two chambers: the Federation Council and the State Duma. The Government is the executive branch and the Constitutional Court is part of the judiciary." },
  b6: { topic: "The cell", q: "What type of cell division turns one diploid cell into four haploid cells?", answers: ["meiosis"],
    exp: "Meiosis consists of two divisions in a row, and the chromosome number is halved. Mitosis, by contrast, gives two cells with the same set as the parent cell." },
  b7: { topic: "Genetics", q: "Two heterozygous individuals Aa × Aa are crossed, with complete dominance. What percentage of offspring will show the recessive phenotype?", answers: ["25 percent"],
    exp: "Offspring genotypes: 1 AA : 2 Aa : 1 aa. The recessive trait appears only in aa — 1 out of 4, i.e. 25%." },
  b8: { topic: "Genetics", q: "How many types of gametes does an individual with genotype AaBb produce if the genes are not linked?", answers: ["four"],
    exp: "The genes are inherited independently, so the gametes are AB, Ab, aB and ab. The general formula is 2ⁿ, where n is the number of heterozygous gene pairs: 2² = 4." },
  b9: { topic: "Evolution", q: "What are organs with a common origin but different functions called (e.g. a human arm and a bat's wing)?", answers: ["homologous", "homologous organs"],
    exp: "Homologous organs are evidence of common descent. Analogous organs, by contrast, do similar jobs but developed from different origins: a butterfly's wing and a bird's wing." },
  b10: { topic: "Ecology", q: "Choose two organisms that are producers. Write the numbers.\n1) birch\n2) brown hare\n3) bracket fungus\n4) Chlamydomonas\n5) wolf",
    exp: "Producers make organic matter from inorganic substances: plants, algae (Chlamydomonas is a single-celled green alga) and cyanobacteria. The hare and the wolf are consumers, and the fungus is a heterotroph." },
  b11: { topic: "Human biology", q: "Which pancreatic hormone lowers blood glucose?", answers: ["insulin"],
    exp: "Insulin helps glucose enter cells and be stored as glycogen. Its antagonist, glucagon, raises blood glucose." },
  c6: { topic: "Atomic structure", q: "How many electrons are in the outer energy level of a phosphorus atom?", answers: ["five"],
    exp: "Phosphorus is in period 3, group VA, with electron distribution 2, 8, 5. For main-group elements the number of outer electrons equals the group number." },
  c7: { topic: "Chemical bonding", q: "Choose two substances with ionic bonds. Write the numbers.\n1) NaCl\n2) HCl\n3) O₂\n4) CaF₂\n5) H₂O",
    exp: "Ionic bonds form between a typical metal and a typical non-metal: NaCl and CaF₂. HCl and H₂O have polar covalent bonds, O₂ a non-polar covalent bond." },
  c8: { topic: "Calculations", q: "Calculate the mass of 0.5 mol of sulfuric acid H₂SO₄. Give the answer in grams.", answers: ["49 g"],
    exp: "M(H₂SO₄) = 2·1 + 32 + 4·16 = 98 g/mol. m = n·M = 0.5 · 98 = 49 g." },
  c9: { topic: "Calculations", q: "20 g of salt were dissolved in 180 g of water. Calculate the mass fraction of salt in the solution (in percent).", answers: ["10 percent"],
    exp: "Mass of solution = 180 + 20 = 200 g. ω = 20 / 200 · 100% = 10%. A common mistake is dividing by the mass of water instead of the solution." },
  c10: { topic: "Reactions", q: "What is the reaction between an acid and a base that produces a salt and water called?", answers: ["neutralization", "neutralisation", "neutralization reaction"],
    exp: "Example: NaOH + HCl → NaCl + H₂O. It is a type of exchange reaction; the net ionic equation is H⁺ + OH⁻ → H₂O." },
  c11: { topic: "Calculations", q: "What volume do 2 mol of any gas occupy at standard conditions? Give the answer in litres.", answers: ["44.8 l"],
    exp: "At standard conditions the molar volume of any gas is Vm = 22.4 L/mol. V = n·Vm = 2 · 22.4 = 44.8 L." },
  p6: { topic: "Kinematics", q: "A car starting from rest accelerates uniformly and reaches 20 m/s in 4 s. Find its acceleration (in m/s²).", answers: ["5 m/s2"],
    exp: "a = (v − v₀) / t = (20 − 0) / 4 = 5 m/s². The initial velocity is zero because the car starts from rest." },
  p7: { topic: "Energy", q: "A 2 kg body moves at 3 m/s. What is its kinetic energy (in joules)?", answers: ["9 j"],
    exp: "Ek = mv²/2 = 2 · 3² / 2 = 9 J. Don't forget to square the velocity — it's the most common mistake." },
  p8: { topic: "Thermodynamics", q: "How much heat is needed to warm 2 kg of water by 10 °C? The specific heat capacity of water is 4200 J/(kg·°C). Give the answer in kilojoules.", answers: ["84 kj"],
    exp: "Q = cmΔt = 4200 · 2 · 10 = 84,000 J = 84 kJ. The answer is asked in kilojoules, so divide by 1000." },
  p9: { topic: "Electricity", q: "Resistors of 3 Ω and 6 Ω are connected in parallel. Find the total resistance (in ohms).", answers: ["2 ohm", "2 ohms"],
    exp: "In parallel 1/R = 1/R₁ + 1/R₂; for two resistors R = R₁R₂ / (R₁ + R₂) = 18 / 9 = 2 Ω. The total is less than the smallest resistance." },
  p10: { topic: "Optics", q: "The focal length of a converging lens is 0.25 m. What is its optical power (in dioptres)?", answers: ["4 d", "4 dioptres", "4 diopters"],
    exp: "D = 1 / F = 1 / 0.25 m = 4 D. The focal length must be in metres." },
  p11: { topic: "General questions", q: "Choose two correct statements. Write the numbers.\n1) In an isobaric process the gas pressure stays constant.\n2) Gravity force is measured in joules.\n3) The speed of light in a vacuum is approximately 3·10⁸ m/s.\n4) In a series connection the total resistance is less than the smallest resistance.\n5) Sound travels through a vacuum.",
    exp: "Statements 1 and 3 are correct. Force is measured in newtons; in series resistances add up, so the total is larger than any of them; sound needs a medium and does not travel through a vacuum." },
  m5: { topic: "Arithmetic", q: "Find the value of (2.4 − 0.9) · 6.", exp: "Brackets first: 2.4 − 0.9 = 1.5. Then 1.5 · 6 = 9." },
  m6: { topic: "Equations", q: "Solve x² − 5x + 6 = 0. If there are several roots, write the larger one.",
    exp: "D = 25 − 24 = 1, x = (5 ± 1) / 2, i.e. 2 and 3. Check with Vieta's theorem: 2 + 3 = 5, 2 · 3 = 6. The larger root is 3." },
  m7: { topic: "Probability", q: "A box contains 20 balls, 5 of them red. Find the probability that a randomly chosen ball is red.",
    exp: "P = favourable outcomes / all outcomes = 5 / 20 = 0.25. In the OGE and EGE the answer is written as a decimal." },
  m8: { topic: "Geometry", q: "The legs of a right triangle are 6 and 8. Find the hypotenuse.",
    exp: "By Pythagoras, c² = 6² + 8² = 36 + 64 = 100, so c = 10. The triple 6, 8, 10 is worth remembering — it's the 3, 4, 5 triple doubled." },
  m9: { topic: "Percentages", q: "An item cost 800 roubles, then its price rose by 15%. How many roubles does it cost now?",
    exp: "15% of 800 is 800 · 0.15 = 120 roubles. The new price is 800 + 120 = 920, or directly 800 · 1.15 = 920." },
  m10: { topic: "Functions", q: "Find the value of the function y = 2x² − 3x at x = −2.",
    exp: "y = 2 · (−2)² − 3 · (−2) = 2 · 4 + 6 = 14. The square of a negative number is positive, and minus times minus gives plus." },
  r5: { topic: "Word stress", q: "Which of these Russian words is stressed on the second syllable: кухонный, щавель, баловать, обеспечение? (type the word in Russian)",
    exp: "Correct stress: щавЕль, кУхонный, баловАть, обеспЕчение. In «обеспечение» the stress falls on the third syllable, as in «баловать»." },
  r6: { topic: "Roots with alternating vowels", q: "Give the numbers of the words where the missing letter is О. Write the numbers.\n1) р..сток\n2) пол..гать\n3) з..ря\n4) к..снуться\n5) выр..щенный",
    exp: "Росток is an exception to the -раст-/-ращ-/-рос- rule, so выращенный is spelled with а. Коснуться takes о because the root is not followed by the suffix -а- (compare касаться). Полагать (before г — а), заря (unstressed — а)." },
  r7: { topic: "Verb spelling", q: "Which ending goes in «Он стара..(тся/ться) успеть к началу урока» ('He tries to make it to the start of the lesson')? Type тся or ться.",
    exp: "Ask the question: он что делает? (what does he do?) — старается. It's a 3rd-person form, so no ь. The soft sign is written in the infinitive: что делать? — стараться." },
  r8: { topic: "Punctuation", q: "How many commas are needed in «Мы шли по дороге и разговаривали а солнце уже садилось за лес» ('We walked along the road and talked, and the sun was already setting behind the forest')? Write a number.", answers: ["one"],
    exp: "«Шли и разговаривали» are coordinate predicates joined by a single и, so no comma. Before а two clauses (subject + predicate pairs) are joined, so a comma is needed: «…разговаривали, а солнце уже садилось за лес»." },
  r9: { topic: "Vocabulary", q: "Which verb fits «… пальто» ('to put on a coat' on yourself): надеть or одеть? (type the word in Russian)",
    exp: "Надеть is used for putting something on (a coat, a hat), одеть for dressing someone (a child, a doll). Mnemonic: «Надеть одежду, одеть Надежду»." },
  r10: { topic: "Vocabulary", q: "What are words that sound and are spelled the same but have completely unrelated meanings called (ключ 'key' and ключ 'spring')?", answers: ["homonyms"],
    exp: "These are homonyms (омонимы): their meanings are unrelated. A polysemous word, by contrast, has meanings linked by a shared feature (the leg of a chair and a person's leg)." },
};
