// Информатика: задания тренажёра в формате ОГЭ и ЕГЭ (часть с кратким ответом).
// Все ответы пересчитаны программой. Темы — по кодификатору ФИПИ.
import type { Task } from "./tasks";

type TaskEnX = { topic: string; q: string; answers?: string[]; exp: string };

export const TASKS_INF: Task[] = [
  {id:"i1", subj:"inf", topic:"Системы счисления", q:"Переведите число 45 из десятичной системы счисления в двоичную.", answers:["101101","101101₂"],
   exp:"Делим на 2 и записываем остатки: 45→1, 22→0, 11→1, 5→1, 2→0, 1→1. Читаем остатки снизу вверх: 101101. Проверка: 32 + 8 + 4 + 1 = 45."},
  {id:"i2", subj:"inf", topic:"Системы счисления", q:"Сколько единиц в двоичной записи числа 100?", answers:["3","три"],
   exp:"100 = 64 + 32 + 4, то есть 100₁₀ = 1100100₂. Единиц три. Быстрый способ — разложить число на степени двойки."},
  {id:"i3", subj:"inf", topic:"Системы счисления", q:"Переведите число 1A из шестнадцатеричной системы счисления в десятичную.", answers:["26"],
   exp:"A₁₆ = 10. 1A₁₆ = 1 · 16 + 10 = 26."},
  {id:"i4", subj:"inf", topic:"Кодирование информации", q:"Текст содержит 2048 символов, каждый символ кодируется 8 битами. Каков информационный объём текста в килобайтах?", answers:["2","2 кбайт","2 кб"],
   exp:"I = K · i = 2048 · 8 бит = 2048 байт. 2048 байт / 1024 = 2 Кбайт. Помните: 1 байт = 8 бит, 1 Кбайт = 1024 байта."},
  {id:"i5", subj:"inf", topic:"Кодирование информации", q:"Алфавит содержит 32 символа. Какое наименьшее число бит нужно, чтобы закодировать один символ этого алфавита одинаковой длиной кода?", answers:["5","5 бит"],
   exp:"По формуле N = 2ⁱ: 32 = 2⁵, значит i = 5 бит. Если бы символов было 33, понадобилось бы уже 6 бит."},
  {id:"i6", subj:"inf", topic:"Кодирование информации", q:"Растровое изображение размером 640×480 пикселей использует палитру из 256 цветов. Каков информационный объём изображения в килобайтах (без учёта сжатия и заголовка)?", answers:["300","300 кбайт","300 кб"],
   exp:"256 = 2⁸, значит на пиксель 8 бит = 1 байт. 640 · 480 = 307 200 байт. 307 200 / 1024 = 300 Кбайт."},
  {id:"i7", subj:"inf", topic:"Передача информации", q:"Файл размером 500 Кбайт передаётся по каналу со скоростью 256 000 бит/с. За сколько секунд передастся файл?", answers:["16","16 с","16 сек"],
   exp:"Переводим объём в биты: 500 · 1024 · 8 = 4 096 000 бит. t = I / v = 4 096 000 / 256 000 = 16 с."},
  {id:"i8", subj:"inf", topic:"Логика", q:"Чему равно значение логического выражения ¬(A ∧ B) ∨ C при A = 1, B = 1, C = 0? Запишите 0 или 1.", answers:["0","ложь"],
   exp:"A ∧ B = 1 ∧ 1 = 1, отрицание даёт ¬1 = 0. Затем 0 ∨ C = 0 ∨ 0 = 0. Дизъюнкция ложна, только когда обе части ложны — как здесь."},
  {id:"i9", subj:"inf", topic:"Логика", q:"Напишите наименьшее целое число x, для которого истинно высказывание: НЕ (x < 7) И (x чётное).", answers:["8"],
   exp:"НЕ (x < 7) означает x ≥ 7. Нужно чётное число не меньше 7: 7 нечётное, следующее — 8."},
  {id:"i10", subj:"inf", topic:"Алгоритмы", q:"У исполнителя две команды: 1 — прибавь 3, 2 — умножь на 2. Какое число получится из числа 1 после выполнения программы 21121?", answers:["19"],
   exp:"Выполняем по порядку: 1 ·2 = 2; +3 = 5; +3 = 8; ·2 = 16; +3 = 19."},
  {id:"i11", subj:"inf", topic:"Алгоритмы", q:"Функция задана так: F(1) = 1, F(2) = 2, F(n) = F(n − 1) + F(n − 2) при n > 2. Чему равно F(6)?", answers:["13"],
   exp:"Считаем снизу вверх: F(3) = 2 + 1 = 3, F(4) = 3 + 2 = 5, F(5) = 5 + 3 = 8, F(6) = 8 + 5 = 13. Рекурсию удобнее разворачивать с маленьких n."},
  {id:"i12", subj:"inf", topic:"Программирование", q:"Что выведет программа на Python?\n\ns = 0\nfor i in range(1, 6):\n    s += i * 2\nprint(s)", answers:["30"],
   exp:"range(1, 6) — это 1, 2, 3, 4, 5 (правая граница не входит). s = 2 + 4 + 6 + 8 + 10 = 30."},
  {id:"i13", subj:"inf", topic:"Программирование", q:"Что выведет программа на Python?\n\nx = 7\nif x % 2 == 0:\n    x = x // 2\nelse:\n    x = 3 * x + 1\nprint(x)", answers:["22"],
   exp:"7 % 2 = 1 — число нечётное, поэтому выполняется ветка else: 3 · 7 + 1 = 22. Оператор % — остаток от деления, // — целая часть."},
  {id:"i14", subj:"inf", topic:"Комбинаторика", q:"Сколько различных слов длиной 4 буквы можно составить из букв А, Б, В, если буквы могут повторяться?", answers:["81"],
   exp:"На каждое из 4 мест можно поставить любую из 3 букв: 3 · 3 · 3 · 3 = 3⁴ = 81."},
  {id:"i15", subj:"inf", topic:"Электронные таблицы", q:"В ячейке A1 записано число 5, в ячейке B1 — число 3. Какое значение появится в ячейке C1, если в ней записана формула =A1*2+B1?", answers:["13"],
   exp:"Сначала умножение: 5 · 2 = 10, затем сложение: 10 + 3 = 13."},
  {id:"i16", subj:"inf", topic:"Электронные таблицы", q:"В ячейке C1 записана формула =$A1+B$1. Её скопировали в ячейку D2. Какой вид примет формула в D2?", answers:["=$A2+C$1","$A2+C$1"],
   exp:"При копировании на один столбец вправо и одну строку вниз меняются только части ссылок без знака $. В $A1 закреплён столбец, меняется строка → $A2. В B$1 закреплена строка, меняется столбец → C$1."},
];

export const EN_INF: Record<string, TaskEnX> = {
  i1: { topic: "Number systems", q: "Convert 45 from decimal to binary.",
    exp: "Divide by 2 and write down the remainders: 45→1, 22→0, 11→1, 5→1, 2→0, 1→1. Read them bottom-up: 101101. Check: 32 + 8 + 4 + 1 = 45." },
  i2: { topic: "Number systems", q: "How many ones are in the binary representation of 100?", answers: ["three"],
    exp: "100 = 64 + 32 + 4, so 100₁₀ = 1100100₂ — three ones. Splitting a number into powers of two is the quickest way." },
  i3: { topic: "Number systems", q: "Convert 1A from hexadecimal to decimal.",
    exp: "A₁₆ = 10, so 1A₁₆ = 1 · 16 + 10 = 26." },
  i4: { topic: "Information encoding", q: "A text has 2048 characters and each character is encoded with 8 bits. What is the size of the text in kilobytes?", answers: ["2 kb", "2 kib"],
    exp: "I = K · i = 2048 · 8 bits = 2048 bytes. 2048 bytes / 1024 = 2 KB. Remember: 1 byte = 8 bits, 1 KB = 1024 bytes (as in the Russian exam)." },
  i5: { topic: "Information encoding", q: "An alphabet has 32 characters. What is the smallest number of bits needed to encode one character with a fixed-length code?", answers: ["5 bits"],
    exp: "By N = 2ⁱ: 32 = 2⁵, so i = 5 bits. With 33 characters you would already need 6 bits." },
  i6: { topic: "Information encoding", q: "A 640×480-pixel bitmap uses a 256-colour palette. What is its size in kilobytes (no compression, no header)?", answers: ["300 kb", "300 kib"],
    exp: "256 = 2⁸, so each pixel takes 8 bits = 1 byte. 640 · 480 = 307,200 bytes. 307,200 / 1024 = 300 KB." },
  i7: { topic: "Data transfer", q: "A 500 KB file is sent over a channel at 256,000 bit/s. How many seconds does it take?", answers: ["16 s", "16 sec"],
    exp: "Convert the size to bits: 500 · 1024 · 8 = 4,096,000 bits. t = I / v = 4,096,000 / 256,000 = 16 s." },
  i8: { topic: "Logic", q: "What is the value of ¬(A ∧ B) ∨ C when A = 1, B = 1, C = 0? Write 0 or 1.", answers: ["false"],
    exp: "A ∧ B = 1 ∧ 1 = 1, and the negation gives ¬1 = 0. Then 0 ∨ C = 0 ∨ 0 = 0. A disjunction is false only when both parts are false — as here." },
  i9: { topic: "Logic", q: "Write the smallest integer x for which the statement is true: NOT (x < 7) AND (x is even).",
    exp: "NOT (x < 7) means x ≥ 7. We need an even number of at least 7: 7 is odd, the next one is 8." },
  i10: { topic: "Algorithms", q: "A robot has two commands: 1 — add 3, 2 — multiply by 2. What number do you get from 1 after running the program 21121?",
    exp: "Run them in order: 1 ·2 = 2; +3 = 5; +3 = 8; ·2 = 16; +3 = 19." },
  i11: { topic: "Algorithms", q: "A function is defined as F(1) = 1, F(2) = 2, F(n) = F(n − 1) + F(n − 2) for n > 2. What is F(6)?",
    exp: "Work upwards: F(3) = 2 + 1 = 3, F(4) = 3 + 2 = 5, F(5) = 5 + 3 = 8, F(6) = 8 + 5 = 13. Unrolling a recursion from small n is the easiest way." },
  i12: { topic: "Programming", q: "What does this Python program print?\n\ns = 0\nfor i in range(1, 6):\n    s += i * 2\nprint(s)",
    exp: "range(1, 6) is 1, 2, 3, 4, 5 (the upper bound is excluded). s = 2 + 4 + 6 + 8 + 10 = 30." },
  i13: { topic: "Programming", q: "What does this Python program print?\n\nx = 7\nif x % 2 == 0:\n    x = x // 2\nelse:\n    x = 3 * x + 1\nprint(x)",
    exp: "7 % 2 = 1 — the number is odd, so the else branch runs: 3 · 7 + 1 = 22. % is the remainder, // is integer division." },
  i14: { topic: "Combinatorics", q: "How many different 4-letter words can be made from the letters A, B, C if letters may repeat?",
    exp: "Each of the 4 positions can hold any of the 3 letters: 3 · 3 · 3 · 3 = 3⁴ = 81." },
  i15: { topic: "Spreadsheets", q: "Cell A1 contains 5 and cell B1 contains 3. What value appears in C1 if it holds the formula =A1*2+B1?",
    exp: "Multiplication first: 5 · 2 = 10, then addition: 10 + 3 = 13." },
  i16: { topic: "Spreadsheets", q: "Cell C1 contains the formula =$A1+B$1. It is copied to D2. What does the formula look like in D2?",
    exp: "Copying one column right and one row down changes only the parts of references without $. In $A1 the column is fixed and the row changes → $A2. In B$1 the row is fixed and the column changes → C$1." },
};
